import {
  SETTINGS_INDEX,
  SETTINGS_PAGES,
  type SettingsEntry,
} from "@/client/components/settings/settings-index";
import { formatAcceleratorFor } from "@/client/lib/format-accelerator";
import { SCREENS } from "@/shared/instrument-screens";
import {
  SHORTCUT_GUIDE_ENTRIES,
  SHORTCUT_GUIDE_GROUPS,
} from "@/shared/shortcut-guide";
import { APP_NAME, APP_NAME_SLUG } from "@instrument-org/shared";

/**
 * The part of the product guide skill that is read off the app rather than
 * written: every page and row of Settings, every screen a link can open, and
 * every keyboard shortcut, each with the address that links to it. A test
 * keeps the skill's `reference.md` equal to this, so a setting added to the
 * index is one the agent can find and link the day it ships.
 */
export function productGuideReference(): string {
  return [
    "<!-- Generated by apps/studio/src/client/lib/product-guide.test.ts from the app's settings index, screens and shortcut tables. Do not edit by hand: run that test with -u. -->",
    "",
    `# ${APP_NAME} reference`,
    "",
    settingsSection(),
    screensSection(),
    shortcutsSection(),
  ].join("\n");
}

function settingsSection() {
  const lines = [
    "## Settings",
    "",
    `Link a page or a row as \`[Label](${APP_NAME_SLUG}://settings/<name>)\`, with the name in backticks below. Settings opens at it, and a row is scrolled to and lit. Settings opens with ⌘, on a Mac (Ctrl+, elsewhere).`,
    "",
  ];
  for (const [tab, page] of Object.entries(SETTINGS_PAGES)) {
    if (page.developerOnly) {
      continue;
    }
    lines.push(`### ${tab} (\`${tab.toLowerCase()}\`)`, "", page.detail);
    if (page.shownWhen) {
      lines.push(
        "",
        `The sidebar lists this page only when ${page.shownWhen}, though a link opens it either way.`,
      );
    }
    lines.push("");
    const rows = SETTINGS_INDEX.filter(
      (entry): entry is Extract<typeof entry, { detail: string }> =>
        entry.tab === tab && "detail" in entry && !isDeveloperOnly(entry),
    );
    for (const row of rows) {
      const labels = SETTINGS_INDEX.filter(
        (entry) => "mark" in entry && entry.mark === row.id,
      ).map((entry) => `${entry.title} (\`${entry.id}\`)`);
      lines.push(
        `- **${row.title}** (\`${row.id}\`): ${sentence(row.detail)}${
          labels.length > 0 ? ` On it: ${labels.join(", ")}.` : ""
        }`,
      );
    }
    if (rows.length > 0) {
      lines.push("");
    }
  }
  return lines.join("\n");
}

function screensSection() {
  return [
    "## Screens",
    "",
    `Link one as \`[Label](${APP_NAME_SLUG}://screen/<name>)\`.`,
    "",
    ...Object.entries(SCREENS).map(
      ([name, screen]) =>
        `- **${screen.title}** (\`${name}\`): ${screen.detail}`,
    ),
    "",
  ].join("\n");
}

function shortcutsSection() {
  const lines = [
    "## Keyboard shortcuts",
    "",
    "Each is written as on a Mac, then as on Windows and Linux.",
    "",
  ];
  for (const group of SHORTCUT_GUIDE_GROUPS) {
    if (group === "Developer") {
      continue;
    }
    lines.push(`### ${group}`, "");
    for (const entry of SHORTCUT_GUIDE_ENTRIES.filter(
      (shortcut) => shortcut.group === group,
    ).toSorted((a, b) => a.label.localeCompare(b.label))) {
      const mac = formatAcceleratorFor({
        accelerator: entry.accelerator,
        isMac: true,
      }).join("");
      const other = formatAcceleratorFor({
        accelerator: entry.accelerator,
        isMac: false,
      }).join("+");
      lines.push(`- ${entry.label}: ${mac} / ${other}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function isDeveloperOnly(entry: SettingsEntry) {
  return entry.developerOnly === true;
}

/** A detail as a sentence, since some are written as a phrase. */
function sentence(text: string) {
  return /[.!?]$/.test(text) ? text : `${text}.`;
}
