/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as DebugRouteRouteImport } from './routes/debug/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AppBrowserRouteImport } from './routes/_app/browser'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppNewTabRouteImport } from './routes/_app/new-tab'
import { Route as AppReleaseNotesRouteImport } from './routes/_app/release-notes'
import { Route as DebugIndexRouteImport } from './routes/debug/index'
import { Route as DebugBrowserViewsRouteImport } from './routes/debug/browser-views'
import { Route as DebugComponentsRouteImport } from './routes/debug/components'
import { Route as DebugErrorsRouteImport } from './routes/debug/errors'
import { Route as DebugNotificationsRouteImport } from './routes/debug/notifications'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingProvidersRouteImport } from './routes/onboarding/providers'
import { Route as OnboardingThemeRouteImport } from './routes/onboarding/theme'
import { Route as AppAppsIndexRouteImport } from './routes/_app/apps/index'
import { Route as AppAppsSlugRouteImport } from './routes/_app/apps/$slug'
import { Route as AppChatsIndexRouteImport } from './routes/_app/chats/index'
import { Route as AppChatsIdRouteImport } from './routes/_app/chats/$id'
import { Route as AppSitesIdRouteImport } from './routes/_app/sites/$id'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppTasksIdRouteImport } from './routes/_app/tasks/$id'
import { Route as DebugBrowserViewTargetIdRouteImport } from './routes/debug/browser-view.$targetId'
import { Route as DebugComponentsIndexRouteImport } from './routes/debug/components/index'
import { Route as DebugComponentsAlertsRouteImport } from './routes/debug/components/alerts'
import { Route as DebugComponentsAppIconsRouteImport } from './routes/debug/components/app-icons'
import { Route as DebugComponentsColorsRouteImport } from './routes/debug/components/colors'
import { Route as DebugComponentsErrorCardRouteImport } from './routes/debug/components/error-card'
import { Route as DebugComponentsFileIconsRouteImport } from './routes/debug/components/file-icons'
import { Route as DebugComponentsFormElementsRouteImport } from './routes/debug/components/form-elements'
import { Route as DebugComponentsModelNoticesRouteImport } from './routes/debug/components/model-notices'
import { Route as DebugComponentsOnboardingRouteImport } from './routes/debug/components/onboarding'
import { Route as DebugComponentsProviderIconsRouteImport } from './routes/debug/components/provider-icons'
import { Route as DebugComponentsQuestionRouteImport } from './routes/debug/components/question'
import { Route as DebugComponentsSpinnerRouteImport } from './routes/debug/components/spinner'
import { Route as DebugComponentsTranscriptRouteImport } from './routes/debug/components/transcript'
import { Route as DebugComponentsTypographyRouteImport } from './routes/debug/components/typography'
import { Route as DebugComponentsOnboardingIndexRouteImport } from './routes/debug/components/onboarding/index'
import { Route as DebugComponentsOnboardingCompleteRouteImport } from './routes/debug/components/onboarding/complete'
import { Route as DebugComponentsOnboardingLoginRouteImport } from './routes/debug/components/onboarding/login'
import { Route as DebugComponentsOnboardingProvidersRouteImport } from './routes/debug/components/onboarding/providers'
import { Route as DebugComponentsOnboardingThemeRouteImport } from './routes/debug/components/onboarding/theme'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRouteRoute = DebugRouteRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBrowserRoute = AppBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewTabRoute = AppNewTabRouteImport.update({
  id: '/new-tab',
  path: '/new-tab',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReleaseNotesRoute = AppReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const DebugIndexRoute = DebugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DebugRouteRoute,
} as any)
const DebugBrowserViewsRoute = DebugBrowserViewsRouteImport.update({
  id: '/browser-views',
  path: '/browser-views',
  getParentRoute: () => DebugRouteRoute,
} as any)
const DebugComponentsRoute = DebugComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DebugRouteRoute,
} as any)
const DebugErrorsRoute = DebugErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DebugRouteRoute,
} as any)
const DebugNotificationsRoute = DebugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DebugRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProvidersRoute = OnboardingProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingThemeRoute = OnboardingThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppsSlugRoute = AppAppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatsIdRoute = AppChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSitesIdRoute = AppSitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const DebugBrowserViewTargetIdRoute =
  DebugBrowserViewTargetIdRouteImport.update({
    id: '/browser-view/$targetId',
    path: '/browser-view/$targetId',
    getParentRoute: () => DebugRouteRoute,
  } as any)
const DebugComponentsIndexRoute = DebugComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DebugComponentsRoute,
} as any)
const DebugComponentsAlertsRoute = DebugComponentsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DebugComponentsRoute,
} as any)
const DebugComponentsAppIconsRoute = DebugComponentsAppIconsRouteImport.update({
  id: '/app-icons',
  path: '/app-icons',
  getParentRoute: () => DebugComponentsRoute,
} as any)
const DebugComponentsColorsRoute = DebugComponentsColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DebugComponentsRoute,
} as any)
const DebugComponentsErrorCardRoute =
  DebugComponentsErrorCardRouteImport.update({
    id: '/error-card',
    path: '/error-card',
    getParentRoute: () => DebugComponentsRoute,
  } as any)
const DebugComponentsFileIconsRoute =
  DebugComponentsFileIconsRouteImport.update({
    id: '/file-icons',
    path: '/file-icons',
    getParentRoute: () => DebugComponentsRoute,
  } as any)
const DebugComponentsFormElementsRoute =
  DebugComponentsFormElementsRouteImport.update({
    id: '/form-elements',
    path: '/form-elements',
    getParentRoute: () => DebugComponentsRoute,
  } as any)
const DebugComponentsModelNoticesRoute =
  DebugComponentsModelNoticesRouteImport.update({
    id: '/model-notices',
    path: '/model-notices',
    getParentRoute: () => DebugComponentsRoute,
  } as any)
const DebugComponentsOnboardingRoute =
  DebugComponentsOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => DebugComponentsRoute,
  } as any)
const DebugComponentsProviderIconsRoute =
  DebugComponentsProviderIconsRouteImport.update({
    id: '/provider-icons',
    path: '/provider-icons',
    getParentRoute: () => DebugComponentsRoute,
  } as any)
const DebugComponentsQuestionRoute = DebugComponentsQuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => DebugComponentsRoute,
} as any)
const DebugComponentsSpinnerRoute = DebugComponentsSpinnerRouteImport.update({
  id: '/spinner',
  path: '/spinner',
  getParentRoute: () => DebugComponentsRoute,
} as any)
const DebugComponentsTranscriptRoute =
  DebugComponentsTranscriptRouteImport.update({
    id: '/transcript',
    path: '/transcript',
    getParentRoute: () => DebugComponentsRoute,
  } as any)
const DebugComponentsTypographyRoute =
  DebugComponentsTypographyRouteImport.update({
    id: '/typography',
    path: '/typography',
    getParentRoute: () => DebugComponentsRoute,
  } as any)
const DebugComponentsOnboardingIndexRoute =
  DebugComponentsOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DebugComponentsOnboardingRoute,
  } as any)
const DebugComponentsOnboardingCompleteRoute =
  DebugComponentsOnboardingCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => DebugComponentsOnboardingRoute,
  } as any)
const DebugComponentsOnboardingLoginRoute =
  DebugComponentsOnboardingLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => DebugComponentsOnboardingRoute,
  } as any)
const DebugComponentsOnboardingProvidersRoute =
  DebugComponentsOnboardingProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => DebugComponentsOnboardingRoute,
  } as any)
const DebugComponentsOnboardingThemeRoute =
  DebugComponentsOnboardingThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => DebugComponentsOnboardingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/browser': typeof AppBrowserRoute
  '/files': typeof AppFilesRoute
  '/new-tab': typeof AppNewTabRoute
  '/release-notes': typeof AppReleaseNotesRoute
  '/debug/browser-views': typeof DebugBrowserViewsRoute
  '/debug/components': typeof DebugComponentsRouteWithChildren
  '/debug/errors': typeof DebugErrorsRoute
  '/debug/notifications': typeof DebugNotificationsRoute
  '/onboarding/providers': typeof OnboardingProvidersRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/debug/': typeof DebugIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/apps/$slug': typeof AppAppsSlugRoute
  '/chats/$id': typeof AppChatsIdRoute
  '/sites/$id': typeof AppSitesIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/debug/browser-view/$targetId': typeof DebugBrowserViewTargetIdRoute
  '/debug/components/alerts': typeof DebugComponentsAlertsRoute
  '/debug/components/app-icons': typeof DebugComponentsAppIconsRoute
  '/debug/components/colors': typeof DebugComponentsColorsRoute
  '/debug/components/error-card': typeof DebugComponentsErrorCardRoute
  '/debug/components/file-icons': typeof DebugComponentsFileIconsRoute
  '/debug/components/form-elements': typeof DebugComponentsFormElementsRoute
  '/debug/components/model-notices': typeof DebugComponentsModelNoticesRoute
  '/debug/components/onboarding': typeof DebugComponentsOnboardingRouteWithChildren
  '/debug/components/provider-icons': typeof DebugComponentsProviderIconsRoute
  '/debug/components/question': typeof DebugComponentsQuestionRoute
  '/debug/components/spinner': typeof DebugComponentsSpinnerRoute
  '/debug/components/transcript': typeof DebugComponentsTranscriptRoute
  '/debug/components/typography': typeof DebugComponentsTypographyRoute
  '/apps/': typeof AppAppsIndexRoute
  '/chats/': typeof AppChatsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/debug/components/': typeof DebugComponentsIndexRoute
  '/debug/components/onboarding/complete': typeof DebugComponentsOnboardingCompleteRoute
  '/debug/components/onboarding/login': typeof DebugComponentsOnboardingLoginRoute
  '/debug/components/onboarding/providers': typeof DebugComponentsOnboardingProvidersRoute
  '/debug/components/onboarding/theme': typeof DebugComponentsOnboardingThemeRoute
  '/debug/components/onboarding/': typeof DebugComponentsOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browser': typeof AppBrowserRoute
  '/files': typeof AppFilesRoute
  '/new-tab': typeof AppNewTabRoute
  '/release-notes': typeof AppReleaseNotesRoute
  '/debug/browser-views': typeof DebugBrowserViewsRoute
  '/debug/errors': typeof DebugErrorsRoute
  '/debug/notifications': typeof DebugNotificationsRoute
  '/onboarding/providers': typeof OnboardingProvidersRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/debug': typeof DebugIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/apps/$slug': typeof AppAppsSlugRoute
  '/chats/$id': typeof AppChatsIdRoute
  '/sites/$id': typeof AppSitesIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/debug/browser-view/$targetId': typeof DebugBrowserViewTargetIdRoute
  '/debug/components/alerts': typeof DebugComponentsAlertsRoute
  '/debug/components/app-icons': typeof DebugComponentsAppIconsRoute
  '/debug/components/colors': typeof DebugComponentsColorsRoute
  '/debug/components/error-card': typeof DebugComponentsErrorCardRoute
  '/debug/components/file-icons': typeof DebugComponentsFileIconsRoute
  '/debug/components/form-elements': typeof DebugComponentsFormElementsRoute
  '/debug/components/model-notices': typeof DebugComponentsModelNoticesRoute
  '/debug/components/provider-icons': typeof DebugComponentsProviderIconsRoute
  '/debug/components/question': typeof DebugComponentsQuestionRoute
  '/debug/components/spinner': typeof DebugComponentsSpinnerRoute
  '/debug/components/transcript': typeof DebugComponentsTranscriptRoute
  '/debug/components/typography': typeof DebugComponentsTypographyRoute
  '/apps': typeof AppAppsIndexRoute
  '/chats': typeof AppChatsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/debug/components': typeof DebugComponentsIndexRoute
  '/debug/components/onboarding/complete': typeof DebugComponentsOnboardingCompleteRoute
  '/debug/components/onboarding/login': typeof DebugComponentsOnboardingLoginRoute
  '/debug/components/onboarding/providers': typeof DebugComponentsOnboardingProvidersRoute
  '/debug/components/onboarding/theme': typeof DebugComponentsOnboardingThemeRoute
  '/debug/components/onboarding': typeof DebugComponentsOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/debug': typeof DebugRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/_app/browser': typeof AppBrowserRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/new-tab': typeof AppNewTabRoute
  '/_app/release-notes': typeof AppReleaseNotesRoute
  '/debug/browser-views': typeof DebugBrowserViewsRoute
  '/debug/components': typeof DebugComponentsRouteWithChildren
  '/debug/errors': typeof DebugErrorsRoute
  '/debug/notifications': typeof DebugNotificationsRoute
  '/onboarding/providers': typeof OnboardingProvidersRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/debug/': typeof DebugIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/apps/$slug': typeof AppAppsSlugRoute
  '/_app/chats/$id': typeof AppChatsIdRoute
  '/_app/sites/$id': typeof AppSitesIdRoute
  '/_app/tasks/$id': typeof AppTasksIdRoute
  '/debug/browser-view/$targetId': typeof DebugBrowserViewTargetIdRoute
  '/debug/components/alerts': typeof DebugComponentsAlertsRoute
  '/debug/components/app-icons': typeof DebugComponentsAppIconsRoute
  '/debug/components/colors': typeof DebugComponentsColorsRoute
  '/debug/components/error-card': typeof DebugComponentsErrorCardRoute
  '/debug/components/file-icons': typeof DebugComponentsFileIconsRoute
  '/debug/components/form-elements': typeof DebugComponentsFormElementsRoute
  '/debug/components/model-notices': typeof DebugComponentsModelNoticesRoute
  '/debug/components/onboarding': typeof DebugComponentsOnboardingRouteWithChildren
  '/debug/components/provider-icons': typeof DebugComponentsProviderIconsRoute
  '/debug/components/question': typeof DebugComponentsQuestionRoute
  '/debug/components/spinner': typeof DebugComponentsSpinnerRoute
  '/debug/components/transcript': typeof DebugComponentsTranscriptRoute
  '/debug/components/typography': typeof DebugComponentsTypographyRoute
  '/_app/apps/': typeof AppAppsIndexRoute
  '/_app/chats/': typeof AppChatsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/debug/components/': typeof DebugComponentsIndexRoute
  '/debug/components/onboarding/complete': typeof DebugComponentsOnboardingCompleteRoute
  '/debug/components/onboarding/login': typeof DebugComponentsOnboardingLoginRoute
  '/debug/components/onboarding/providers': typeof DebugComponentsOnboardingProvidersRoute
  '/debug/components/onboarding/theme': typeof DebugComponentsOnboardingThemeRoute
  '/debug/components/onboarding/': typeof DebugComponentsOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/onboarding'
    | '/browser'
    | '/files'
    | '/new-tab'
    | '/release-notes'
    | '/debug/browser-views'
    | '/debug/components'
    | '/debug/errors'
    | '/debug/notifications'
    | '/onboarding/providers'
    | '/onboarding/theme'
    | '/debug/'
    | '/onboarding/'
    | '/apps/$slug'
    | '/chats/$id'
    | '/sites/$id'
    | '/tasks/$id'
    | '/debug/browser-view/$targetId'
    | '/debug/components/alerts'
    | '/debug/components/app-icons'
    | '/debug/components/colors'
    | '/debug/components/error-card'
    | '/debug/components/file-icons'
    | '/debug/components/form-elements'
    | '/debug/components/model-notices'
    | '/debug/components/onboarding'
    | '/debug/components/provider-icons'
    | '/debug/components/question'
    | '/debug/components/spinner'
    | '/debug/components/transcript'
    | '/debug/components/typography'
    | '/apps/'
    | '/chats/'
    | '/tasks/'
    | '/debug/components/'
    | '/debug/components/onboarding/complete'
    | '/debug/components/onboarding/login'
    | '/debug/components/onboarding/providers'
    | '/debug/components/onboarding/theme'
    | '/debug/components/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browser'
    | '/files'
    | '/new-tab'
    | '/release-notes'
    | '/debug/browser-views'
    | '/debug/errors'
    | '/debug/notifications'
    | '/onboarding/providers'
    | '/onboarding/theme'
    | '/debug'
    | '/onboarding'
    | '/apps/$slug'
    | '/chats/$id'
    | '/sites/$id'
    | '/tasks/$id'
    | '/debug/browser-view/$targetId'
    | '/debug/components/alerts'
    | '/debug/components/app-icons'
    | '/debug/components/colors'
    | '/debug/components/error-card'
    | '/debug/components/file-icons'
    | '/debug/components/form-elements'
    | '/debug/components/model-notices'
    | '/debug/components/provider-icons'
    | '/debug/components/question'
    | '/debug/components/spinner'
    | '/debug/components/transcript'
    | '/debug/components/typography'
    | '/apps'
    | '/chats'
    | '/tasks'
    | '/debug/components'
    | '/debug/components/onboarding/complete'
    | '/debug/components/onboarding/login'
    | '/debug/components/onboarding/providers'
    | '/debug/components/onboarding/theme'
    | '/debug/components/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/debug'
    | '/onboarding'
    | '/_app/browser'
    | '/_app/files'
    | '/_app/new-tab'
    | '/_app/release-notes'
    | '/debug/browser-views'
    | '/debug/components'
    | '/debug/errors'
    | '/debug/notifications'
    | '/onboarding/providers'
    | '/onboarding/theme'
    | '/debug/'
    | '/onboarding/'
    | '/_app/apps/$slug'
    | '/_app/chats/$id'
    | '/_app/sites/$id'
    | '/_app/tasks/$id'
    | '/debug/browser-view/$targetId'
    | '/debug/components/alerts'
    | '/debug/components/app-icons'
    | '/debug/components/colors'
    | '/debug/components/error-card'
    | '/debug/components/file-icons'
    | '/debug/components/form-elements'
    | '/debug/components/model-notices'
    | '/debug/components/onboarding'
    | '/debug/components/provider-icons'
    | '/debug/components/question'
    | '/debug/components/spinner'
    | '/debug/components/transcript'
    | '/debug/components/typography'
    | '/_app/apps/'
    | '/_app/chats/'
    | '/_app/tasks/'
    | '/debug/components/'
    | '/debug/components/onboarding/complete'
    | '/debug/components/onboarding/login'
    | '/debug/components/onboarding/providers'
    | '/debug/components/onboarding/theme'
    | '/debug/components/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DebugRouteRoute: typeof DebugRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/browser': {
      id: '/_app/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof AppBrowserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/new-tab': {
      id: '/_app/new-tab'
      path: '/new-tab'
      fullPath: '/new-tab'
      preLoaderRoute: typeof AppNewTabRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/release-notes': {
      id: '/_app/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof AppReleaseNotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/debug/': {
      id: '/debug/'
      path: '/'
      fullPath: '/debug/'
      preLoaderRoute: typeof DebugIndexRouteImport
      parentRoute: typeof DebugRouteRoute
    }
    '/debug/browser-views': {
      id: '/debug/browser-views'
      path: '/browser-views'
      fullPath: '/debug/browser-views'
      preLoaderRoute: typeof DebugBrowserViewsRouteImport
      parentRoute: typeof DebugRouteRoute
    }
    '/debug/components': {
      id: '/debug/components'
      path: '/components'
      fullPath: '/debug/components'
      preLoaderRoute: typeof DebugComponentsRouteImport
      parentRoute: typeof DebugRouteRoute
    }
    '/debug/errors': {
      id: '/debug/errors'
      path: '/errors'
      fullPath: '/debug/errors'
      preLoaderRoute: typeof DebugErrorsRouteImport
      parentRoute: typeof DebugRouteRoute
    }
    '/debug/notifications': {
      id: '/debug/notifications'
      path: '/notifications'
      fullPath: '/debug/notifications'
      preLoaderRoute: typeof DebugNotificationsRouteImport
      parentRoute: typeof DebugRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/providers': {
      id: '/onboarding/providers'
      path: '/providers'
      fullPath: '/onboarding/providers'
      preLoaderRoute: typeof OnboardingProvidersRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/theme': {
      id: '/onboarding/theme'
      path: '/theme'
      fullPath: '/onboarding/theme'
      preLoaderRoute: typeof OnboardingThemeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/apps/$slug': {
      id: '/_app/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppAppsSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/chats/': {
      id: '/_app/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/chats/$id': {
      id: '/_app/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AppChatsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sites/$id': {
      id: '/_app/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof AppSitesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks/$id': {
      id: '/_app/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/debug/browser-view/$targetId': {
      id: '/debug/browser-view/$targetId'
      path: '/browser-view/$targetId'
      fullPath: '/debug/browser-view/$targetId'
      preLoaderRoute: typeof DebugBrowserViewTargetIdRouteImport
      parentRoute: typeof DebugRouteRoute
    }
    '/debug/components/': {
      id: '/debug/components/'
      path: '/'
      fullPath: '/debug/components/'
      preLoaderRoute: typeof DebugComponentsIndexRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/alerts': {
      id: '/debug/components/alerts'
      path: '/alerts'
      fullPath: '/debug/components/alerts'
      preLoaderRoute: typeof DebugComponentsAlertsRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/app-icons': {
      id: '/debug/components/app-icons'
      path: '/app-icons'
      fullPath: '/debug/components/app-icons'
      preLoaderRoute: typeof DebugComponentsAppIconsRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/colors': {
      id: '/debug/components/colors'
      path: '/colors'
      fullPath: '/debug/components/colors'
      preLoaderRoute: typeof DebugComponentsColorsRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/error-card': {
      id: '/debug/components/error-card'
      path: '/error-card'
      fullPath: '/debug/components/error-card'
      preLoaderRoute: typeof DebugComponentsErrorCardRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/file-icons': {
      id: '/debug/components/file-icons'
      path: '/file-icons'
      fullPath: '/debug/components/file-icons'
      preLoaderRoute: typeof DebugComponentsFileIconsRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/form-elements': {
      id: '/debug/components/form-elements'
      path: '/form-elements'
      fullPath: '/debug/components/form-elements'
      preLoaderRoute: typeof DebugComponentsFormElementsRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/model-notices': {
      id: '/debug/components/model-notices'
      path: '/model-notices'
      fullPath: '/debug/components/model-notices'
      preLoaderRoute: typeof DebugComponentsModelNoticesRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/onboarding': {
      id: '/debug/components/onboarding'
      path: '/onboarding'
      fullPath: '/debug/components/onboarding'
      preLoaderRoute: typeof DebugComponentsOnboardingRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/provider-icons': {
      id: '/debug/components/provider-icons'
      path: '/provider-icons'
      fullPath: '/debug/components/provider-icons'
      preLoaderRoute: typeof DebugComponentsProviderIconsRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/question': {
      id: '/debug/components/question'
      path: '/question'
      fullPath: '/debug/components/question'
      preLoaderRoute: typeof DebugComponentsQuestionRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/spinner': {
      id: '/debug/components/spinner'
      path: '/spinner'
      fullPath: '/debug/components/spinner'
      preLoaderRoute: typeof DebugComponentsSpinnerRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/transcript': {
      id: '/debug/components/transcript'
      path: '/transcript'
      fullPath: '/debug/components/transcript'
      preLoaderRoute: typeof DebugComponentsTranscriptRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/typography': {
      id: '/debug/components/typography'
      path: '/typography'
      fullPath: '/debug/components/typography'
      preLoaderRoute: typeof DebugComponentsTypographyRouteImport
      parentRoute: typeof DebugComponentsRoute
    }
    '/debug/components/onboarding/': {
      id: '/debug/components/onboarding/'
      path: '/'
      fullPath: '/debug/components/onboarding/'
      preLoaderRoute: typeof DebugComponentsOnboardingIndexRouteImport
      parentRoute: typeof DebugComponentsOnboardingRoute
    }
    '/debug/components/onboarding/complete': {
      id: '/debug/components/onboarding/complete'
      path: '/complete'
      fullPath: '/debug/components/onboarding/complete'
      preLoaderRoute: typeof DebugComponentsOnboardingCompleteRouteImport
      parentRoute: typeof DebugComponentsOnboardingRoute
    }
    '/debug/components/onboarding/login': {
      id: '/debug/components/onboarding/login'
      path: '/login'
      fullPath: '/debug/components/onboarding/login'
      preLoaderRoute: typeof DebugComponentsOnboardingLoginRouteImport
      parentRoute: typeof DebugComponentsOnboardingRoute
    }
    '/debug/components/onboarding/providers': {
      id: '/debug/components/onboarding/providers'
      path: '/providers'
      fullPath: '/debug/components/onboarding/providers'
      preLoaderRoute: typeof DebugComponentsOnboardingProvidersRouteImport
      parentRoute: typeof DebugComponentsOnboardingRoute
    }
    '/debug/components/onboarding/theme': {
      id: '/debug/components/onboarding/theme'
      path: '/theme'
      fullPath: '/debug/components/onboarding/theme'
      preLoaderRoute: typeof DebugComponentsOnboardingThemeRouteImport
      parentRoute: typeof DebugComponentsOnboardingRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBrowserRoute: typeof AppBrowserRoute
  AppFilesRoute: typeof AppFilesRoute
  AppNewTabRoute: typeof AppNewTabRoute
  AppReleaseNotesRoute: typeof AppReleaseNotesRoute
  AppAppsSlugRoute: typeof AppAppsSlugRoute
  AppChatsIdRoute: typeof AppChatsIdRoute
  AppSitesIdRoute: typeof AppSitesIdRoute
  AppTasksIdRoute: typeof AppTasksIdRoute
  AppAppsIndexRoute: typeof AppAppsIndexRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBrowserRoute: AppBrowserRoute,
  AppFilesRoute: AppFilesRoute,
  AppNewTabRoute: AppNewTabRoute,
  AppReleaseNotesRoute: AppReleaseNotesRoute,
  AppAppsSlugRoute: AppAppsSlugRoute,
  AppChatsIdRoute: AppChatsIdRoute,
  AppSitesIdRoute: AppSitesIdRoute,
  AppTasksIdRoute: AppTasksIdRoute,
  AppAppsIndexRoute: AppAppsIndexRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DebugComponentsOnboardingRouteChildren {
  DebugComponentsOnboardingCompleteRoute: typeof DebugComponentsOnboardingCompleteRoute
  DebugComponentsOnboardingLoginRoute: typeof DebugComponentsOnboardingLoginRoute
  DebugComponentsOnboardingProvidersRoute: typeof DebugComponentsOnboardingProvidersRoute
  DebugComponentsOnboardingThemeRoute: typeof DebugComponentsOnboardingThemeRoute
  DebugComponentsOnboardingIndexRoute: typeof DebugComponentsOnboardingIndexRoute
}

const DebugComponentsOnboardingRouteChildren: DebugComponentsOnboardingRouteChildren =
  {
    DebugComponentsOnboardingCompleteRoute:
      DebugComponentsOnboardingCompleteRoute,
    DebugComponentsOnboardingLoginRoute: DebugComponentsOnboardingLoginRoute,
    DebugComponentsOnboardingProvidersRoute:
      DebugComponentsOnboardingProvidersRoute,
    DebugComponentsOnboardingThemeRoute: DebugComponentsOnboardingThemeRoute,
    DebugComponentsOnboardingIndexRoute: DebugComponentsOnboardingIndexRoute,
  }

const DebugComponentsOnboardingRouteWithChildren =
  DebugComponentsOnboardingRoute._addFileChildren(
    DebugComponentsOnboardingRouteChildren,
  )

interface DebugComponentsRouteChildren {
  DebugComponentsAlertsRoute: typeof DebugComponentsAlertsRoute
  DebugComponentsAppIconsRoute: typeof DebugComponentsAppIconsRoute
  DebugComponentsColorsRoute: typeof DebugComponentsColorsRoute
  DebugComponentsErrorCardRoute: typeof DebugComponentsErrorCardRoute
  DebugComponentsFileIconsRoute: typeof DebugComponentsFileIconsRoute
  DebugComponentsFormElementsRoute: typeof DebugComponentsFormElementsRoute
  DebugComponentsModelNoticesRoute: typeof DebugComponentsModelNoticesRoute
  DebugComponentsOnboardingRoute: typeof DebugComponentsOnboardingRouteWithChildren
  DebugComponentsProviderIconsRoute: typeof DebugComponentsProviderIconsRoute
  DebugComponentsQuestionRoute: typeof DebugComponentsQuestionRoute
  DebugComponentsSpinnerRoute: typeof DebugComponentsSpinnerRoute
  DebugComponentsTranscriptRoute: typeof DebugComponentsTranscriptRoute
  DebugComponentsTypographyRoute: typeof DebugComponentsTypographyRoute
  DebugComponentsIndexRoute: typeof DebugComponentsIndexRoute
}

const DebugComponentsRouteChildren: DebugComponentsRouteChildren = {
  DebugComponentsAlertsRoute: DebugComponentsAlertsRoute,
  DebugComponentsAppIconsRoute: DebugComponentsAppIconsRoute,
  DebugComponentsColorsRoute: DebugComponentsColorsRoute,
  DebugComponentsErrorCardRoute: DebugComponentsErrorCardRoute,
  DebugComponentsFileIconsRoute: DebugComponentsFileIconsRoute,
  DebugComponentsFormElementsRoute: DebugComponentsFormElementsRoute,
  DebugComponentsModelNoticesRoute: DebugComponentsModelNoticesRoute,
  DebugComponentsOnboardingRoute: DebugComponentsOnboardingRouteWithChildren,
  DebugComponentsProviderIconsRoute: DebugComponentsProviderIconsRoute,
  DebugComponentsQuestionRoute: DebugComponentsQuestionRoute,
  DebugComponentsSpinnerRoute: DebugComponentsSpinnerRoute,
  DebugComponentsTranscriptRoute: DebugComponentsTranscriptRoute,
  DebugComponentsTypographyRoute: DebugComponentsTypographyRoute,
  DebugComponentsIndexRoute: DebugComponentsIndexRoute,
}

const DebugComponentsRouteWithChildren = DebugComponentsRoute._addFileChildren(
  DebugComponentsRouteChildren,
)

interface DebugRouteRouteChildren {
  DebugBrowserViewsRoute: typeof DebugBrowserViewsRoute
  DebugComponentsRoute: typeof DebugComponentsRouteWithChildren
  DebugErrorsRoute: typeof DebugErrorsRoute
  DebugNotificationsRoute: typeof DebugNotificationsRoute
  DebugIndexRoute: typeof DebugIndexRoute
  DebugBrowserViewTargetIdRoute: typeof DebugBrowserViewTargetIdRoute
}

const DebugRouteRouteChildren: DebugRouteRouteChildren = {
  DebugBrowserViewsRoute: DebugBrowserViewsRoute,
  DebugComponentsRoute: DebugComponentsRouteWithChildren,
  DebugErrorsRoute: DebugErrorsRoute,
  DebugNotificationsRoute: DebugNotificationsRoute,
  DebugIndexRoute: DebugIndexRoute,
  DebugBrowserViewTargetIdRoute: DebugBrowserViewTargetIdRoute,
}

const DebugRouteRouteWithChildren = DebugRouteRoute._addFileChildren(
  DebugRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingProvidersRoute: typeof OnboardingProvidersRoute
  OnboardingThemeRoute: typeof OnboardingThemeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingProvidersRoute: OnboardingProvidersRoute,
  OnboardingThemeRoute: OnboardingThemeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DebugRouteRoute: DebugRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
