/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioOverlayIdleRouteImport } from './routes/studio-overlay-idle'
import { Route as StudioOverlayRouteImport } from './routes/studio-overlay'
import { Route as ShellRouteImport } from './routes/shell'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as StudioOverlayWelcomeRouteImport } from './routes/studio-overlay/welcome'
import { Route as StudioOverlaySettingsRouteImport } from './routes/studio-overlay/settings'
import { Route as StudioOverlayLoginRouteImport } from './routes/studio-overlay/login'
import { Route as StudioOverlayCrashRouteImport } from './routes/studio-overlay/crash'
import { Route as OnboardingThemeRouteImport } from './routes/onboarding/theme'
import { Route as OnboardingProvidersRouteImport } from './routes/onboarding/providers'
import { Route as AppTutorialTaskRouteImport } from './routes/_app/tutorial-task'
import { Route as AppReleaseNotesRouteImport } from './routes/_app/release-notes'
import { Route as AppNewTabRouteImport } from './routes/_app/new-tab'
import { Route as AppDebugRouteRouteImport } from './routes/_app/debug/route'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/_app/_authenticated/route'
import { Route as StudioOverlaySettingsIndexRouteImport } from './routes/studio-overlay/settings/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppEvalsIndexRouteImport } from './routes/_app/evals/index'
import { Route as AppDebugIndexRouteImport } from './routes/_app/debug/index'
import { Route as StudioOverlaySettingsProvidersRouteImport } from './routes/studio-overlay/settings/providers'
import { Route as StudioOverlaySettingsFeaturesRouteImport } from './routes/studio-overlay/settings/features'
import { Route as StudioOverlaySettingsDebugRouteImport } from './routes/studio-overlay/settings/debug'
import { Route as AppDebugNotificationsRouteImport } from './routes/_app/debug/notifications'
import { Route as AppDebugErrorsRouteImport } from './routes/_app/debug/errors'
import { Route as AppDebugComponentsRouteImport } from './routes/_app/debug/components'
import { Route as AppDebugBrowserViewsRouteImport } from './routes/_app/debug/browser-views'
import { Route as AppAuthenticatedSubscribeRouteImport } from './routes/_app/_authenticated/subscribe'
import { Route as AppTasksIdIndexRouteImport } from './routes/_app/tasks/$id/index'
import { Route as AppProjectsSubdomainIndexRouteImport } from './routes/_app/projects/$subdomain/index'
import { Route as AppDebugComponentsIndexRouteImport } from './routes/_app/debug/components/index'
import { Route as AppDebugComponentsUpdateStatusRouteImport } from './routes/_app/debug/components/update-status'
import { Route as AppDebugComponentsSpinnerRouteImport } from './routes/_app/debug/components/spinner'
import { Route as AppDebugComponentsProviderIconsRouteImport } from './routes/_app/debug/components/provider-icons'
import { Route as AppDebugComponentsOnboardingRouteImport } from './routes/_app/debug/components/onboarding'
import { Route as AppDebugComponentsErrorCardRouteImport } from './routes/_app/debug/components/error-card'
import { Route as AppDebugComponentsColorsRouteImport } from './routes/_app/debug/components/colors'
import { Route as AppDebugComponentsChatStreamRouteImport } from './routes/_app/debug/components/chat-stream'
import { Route as AppDebugComponentsAlertsRouteImport } from './routes/_app/debug/components/alerts'
import { Route as AppDebugBrowserViewTargetIdRouteImport } from './routes/_app/debug/browser-view.$targetId'
import { Route as AppDebugComponentsOnboardingIndexRouteImport } from './routes/_app/debug/components/onboarding/index'
import { Route as AppDebugComponentsOnboardingThemeRouteImport } from './routes/_app/debug/components/onboarding/theme'
import { Route as AppDebugComponentsOnboardingProvidersRouteImport } from './routes/_app/debug/components/onboarding/providers'
import { Route as AppDebugComponentsOnboardingLoginRouteImport } from './routes/_app/debug/components/onboarding/login'
import { Route as AppDebugComponentsOnboardingCompleteRouteImport } from './routes/_app/debug/components/onboarding/complete'

const StudioOverlayIdleRoute = StudioOverlayIdleRouteImport.update({
  id: '/studio-overlay-idle',
  path: '/studio-overlay-idle',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioOverlayRoute = StudioOverlayRouteImport.update({
  id: '/studio-overlay',
  path: '/studio-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const StudioOverlayWelcomeRoute = StudioOverlayWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => StudioOverlayRoute,
} as any)
const StudioOverlaySettingsRoute = StudioOverlaySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioOverlayRoute,
} as any)
const StudioOverlayLoginRoute = StudioOverlayLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StudioOverlayRoute,
} as any)
const StudioOverlayCrashRoute = StudioOverlayCrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => StudioOverlayRoute,
} as any)
const OnboardingThemeRoute = OnboardingThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProvidersRoute = OnboardingProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AppTutorialTaskRoute = AppTutorialTaskRouteImport.update({
  id: '/tutorial-task',
  path: '/tutorial-task',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReleaseNotesRoute = AppReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewTabRoute = AppNewTabRouteImport.update({
  id: '/new-tab',
  path: '/new-tab',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDebugRouteRoute = AppDebugRouteRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const StudioOverlaySettingsIndexRoute =
  StudioOverlaySettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudioOverlaySettingsRoute,
  } as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvalsIndexRoute = AppEvalsIndexRouteImport.update({
  id: '/evals/',
  path: '/evals/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDebugIndexRoute = AppDebugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDebugRouteRoute,
} as any)
const StudioOverlaySettingsProvidersRoute =
  StudioOverlaySettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => StudioOverlaySettingsRoute,
  } as any)
const StudioOverlaySettingsFeaturesRoute =
  StudioOverlaySettingsFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => StudioOverlaySettingsRoute,
  } as any)
const StudioOverlaySettingsDebugRoute =
  StudioOverlaySettingsDebugRouteImport.update({
    id: '/debug',
    path: '/debug',
    getParentRoute: () => StudioOverlaySettingsRoute,
  } as any)
const AppDebugNotificationsRoute = AppDebugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppDebugRouteRoute,
} as any)
const AppDebugErrorsRoute = AppDebugErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AppDebugRouteRoute,
} as any)
const AppDebugComponentsRoute = AppDebugComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppDebugRouteRoute,
} as any)
const AppDebugBrowserViewsRoute = AppDebugBrowserViewsRouteImport.update({
  id: '/browser-views',
  path: '/browser-views',
  getParentRoute: () => AppDebugRouteRoute,
} as any)
const AppAuthenticatedSubscribeRoute =
  AppAuthenticatedSubscribeRouteImport.update({
    id: '/subscribe',
    path: '/subscribe',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppTasksIdIndexRoute = AppTasksIdIndexRouteImport.update({
  id: '/tasks/$id/',
  path: '/tasks/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsSubdomainIndexRoute =
  AppProjectsSubdomainIndexRouteImport.update({
    id: '/projects/$subdomain/',
    path: '/projects/$subdomain/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDebugComponentsIndexRoute = AppDebugComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDebugComponentsRoute,
} as any)
const AppDebugComponentsUpdateStatusRoute =
  AppDebugComponentsUpdateStatusRouteImport.update({
    id: '/update-status',
    path: '/update-status',
    getParentRoute: () => AppDebugComponentsRoute,
  } as any)
const AppDebugComponentsSpinnerRoute =
  AppDebugComponentsSpinnerRouteImport.update({
    id: '/spinner',
    path: '/spinner',
    getParentRoute: () => AppDebugComponentsRoute,
  } as any)
const AppDebugComponentsProviderIconsRoute =
  AppDebugComponentsProviderIconsRouteImport.update({
    id: '/provider-icons',
    path: '/provider-icons',
    getParentRoute: () => AppDebugComponentsRoute,
  } as any)
const AppDebugComponentsOnboardingRoute =
  AppDebugComponentsOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AppDebugComponentsRoute,
  } as any)
const AppDebugComponentsErrorCardRoute =
  AppDebugComponentsErrorCardRouteImport.update({
    id: '/error-card',
    path: '/error-card',
    getParentRoute: () => AppDebugComponentsRoute,
  } as any)
const AppDebugComponentsColorsRoute =
  AppDebugComponentsColorsRouteImport.update({
    id: '/colors',
    path: '/colors',
    getParentRoute: () => AppDebugComponentsRoute,
  } as any)
const AppDebugComponentsChatStreamRoute =
  AppDebugComponentsChatStreamRouteImport.update({
    id: '/chat-stream',
    path: '/chat-stream',
    getParentRoute: () => AppDebugComponentsRoute,
  } as any)
const AppDebugComponentsAlertsRoute =
  AppDebugComponentsAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AppDebugComponentsRoute,
  } as any)
const AppDebugBrowserViewTargetIdRoute =
  AppDebugBrowserViewTargetIdRouteImport.update({
    id: '/browser-view/$targetId',
    path: '/browser-view/$targetId',
    getParentRoute: () => AppDebugRouteRoute,
  } as any)
const AppDebugComponentsOnboardingIndexRoute =
  AppDebugComponentsOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDebugComponentsOnboardingRoute,
  } as any)
const AppDebugComponentsOnboardingThemeRoute =
  AppDebugComponentsOnboardingThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AppDebugComponentsOnboardingRoute,
  } as any)
const AppDebugComponentsOnboardingProvidersRoute =
  AppDebugComponentsOnboardingProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AppDebugComponentsOnboardingRoute,
  } as any)
const AppDebugComponentsOnboardingLoginRoute =
  AppDebugComponentsOnboardingLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => AppDebugComponentsOnboardingRoute,
  } as any)
const AppDebugComponentsOnboardingCompleteRoute =
  AppDebugComponentsOnboardingCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => AppDebugComponentsOnboardingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/shell': typeof ShellRoute
  '/studio-overlay': typeof StudioOverlayRouteWithChildren
  '/studio-overlay-idle': typeof StudioOverlayIdleRoute
  '/debug': typeof AppDebugRouteRouteWithChildren
  '/new-tab': typeof AppNewTabRoute
  '/release-notes': typeof AppReleaseNotesRoute
  '/tutorial-task': typeof AppTutorialTaskRoute
  '/onboarding/providers': typeof OnboardingProvidersRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/studio-overlay/crash': typeof StudioOverlayCrashRoute
  '/studio-overlay/login': typeof StudioOverlayLoginRoute
  '/studio-overlay/settings': typeof StudioOverlaySettingsRouteWithChildren
  '/studio-overlay/welcome': typeof StudioOverlayWelcomeRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/subscribe': typeof AppAuthenticatedSubscribeRoute
  '/debug/browser-views': typeof AppDebugBrowserViewsRoute
  '/debug/components': typeof AppDebugComponentsRouteWithChildren
  '/debug/errors': typeof AppDebugErrorsRoute
  '/debug/notifications': typeof AppDebugNotificationsRoute
  '/studio-overlay/settings/debug': typeof StudioOverlaySettingsDebugRoute
  '/studio-overlay/settings/features': typeof StudioOverlaySettingsFeaturesRoute
  '/studio-overlay/settings/providers': typeof StudioOverlaySettingsProvidersRoute
  '/debug/': typeof AppDebugIndexRoute
  '/evals': typeof AppEvalsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/studio-overlay/settings/': typeof StudioOverlaySettingsIndexRoute
  '/debug/browser-view/$targetId': typeof AppDebugBrowserViewTargetIdRoute
  '/debug/components/alerts': typeof AppDebugComponentsAlertsRoute
  '/debug/components/chat-stream': typeof AppDebugComponentsChatStreamRoute
  '/debug/components/colors': typeof AppDebugComponentsColorsRoute
  '/debug/components/error-card': typeof AppDebugComponentsErrorCardRoute
  '/debug/components/onboarding': typeof AppDebugComponentsOnboardingRouteWithChildren
  '/debug/components/provider-icons': typeof AppDebugComponentsProviderIconsRoute
  '/debug/components/spinner': typeof AppDebugComponentsSpinnerRoute
  '/debug/components/update-status': typeof AppDebugComponentsUpdateStatusRoute
  '/debug/components/': typeof AppDebugComponentsIndexRoute
  '/projects/$subdomain': typeof AppProjectsSubdomainIndexRoute
  '/tasks/$id': typeof AppTasksIdIndexRoute
  '/debug/components/onboarding/complete': typeof AppDebugComponentsOnboardingCompleteRoute
  '/debug/components/onboarding/login': typeof AppDebugComponentsOnboardingLoginRoute
  '/debug/components/onboarding/providers': typeof AppDebugComponentsOnboardingProvidersRoute
  '/debug/components/onboarding/theme': typeof AppDebugComponentsOnboardingThemeRoute
  '/debug/components/onboarding/': typeof AppDebugComponentsOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shell': typeof ShellRoute
  '/studio-overlay': typeof StudioOverlayRouteWithChildren
  '/studio-overlay-idle': typeof StudioOverlayIdleRoute
  '/new-tab': typeof AppNewTabRoute
  '/release-notes': typeof AppReleaseNotesRoute
  '/tutorial-task': typeof AppTutorialTaskRoute
  '/onboarding/providers': typeof OnboardingProvidersRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/studio-overlay/crash': typeof StudioOverlayCrashRoute
  '/studio-overlay/login': typeof StudioOverlayLoginRoute
  '/studio-overlay/welcome': typeof StudioOverlayWelcomeRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/subscribe': typeof AppAuthenticatedSubscribeRoute
  '/debug/browser-views': typeof AppDebugBrowserViewsRoute
  '/debug/errors': typeof AppDebugErrorsRoute
  '/debug/notifications': typeof AppDebugNotificationsRoute
  '/studio-overlay/settings/debug': typeof StudioOverlaySettingsDebugRoute
  '/studio-overlay/settings/features': typeof StudioOverlaySettingsFeaturesRoute
  '/studio-overlay/settings/providers': typeof StudioOverlaySettingsProvidersRoute
  '/debug': typeof AppDebugIndexRoute
  '/evals': typeof AppEvalsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/studio-overlay/settings': typeof StudioOverlaySettingsIndexRoute
  '/debug/browser-view/$targetId': typeof AppDebugBrowserViewTargetIdRoute
  '/debug/components/alerts': typeof AppDebugComponentsAlertsRoute
  '/debug/components/chat-stream': typeof AppDebugComponentsChatStreamRoute
  '/debug/components/colors': typeof AppDebugComponentsColorsRoute
  '/debug/components/error-card': typeof AppDebugComponentsErrorCardRoute
  '/debug/components/provider-icons': typeof AppDebugComponentsProviderIconsRoute
  '/debug/components/spinner': typeof AppDebugComponentsSpinnerRoute
  '/debug/components/update-status': typeof AppDebugComponentsUpdateStatusRoute
  '/debug/components': typeof AppDebugComponentsIndexRoute
  '/projects/$subdomain': typeof AppProjectsSubdomainIndexRoute
  '/tasks/$id': typeof AppTasksIdIndexRoute
  '/debug/components/onboarding/complete': typeof AppDebugComponentsOnboardingCompleteRoute
  '/debug/components/onboarding/login': typeof AppDebugComponentsOnboardingLoginRoute
  '/debug/components/onboarding/providers': typeof AppDebugComponentsOnboardingProvidersRoute
  '/debug/components/onboarding/theme': typeof AppDebugComponentsOnboardingThemeRoute
  '/debug/components/onboarding': typeof AppDebugComponentsOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/shell': typeof ShellRoute
  '/studio-overlay': typeof StudioOverlayRouteWithChildren
  '/studio-overlay-idle': typeof StudioOverlayIdleRoute
  '/_app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/_app/debug': typeof AppDebugRouteRouteWithChildren
  '/_app/new-tab': typeof AppNewTabRoute
  '/_app/release-notes': typeof AppReleaseNotesRoute
  '/_app/tutorial-task': typeof AppTutorialTaskRoute
  '/onboarding/providers': typeof OnboardingProvidersRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/studio-overlay/crash': typeof StudioOverlayCrashRoute
  '/studio-overlay/login': typeof StudioOverlayLoginRoute
  '/studio-overlay/settings': typeof StudioOverlaySettingsRouteWithChildren
  '/studio-overlay/welcome': typeof StudioOverlayWelcomeRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/_authenticated/subscribe': typeof AppAuthenticatedSubscribeRoute
  '/_app/debug/browser-views': typeof AppDebugBrowserViewsRoute
  '/_app/debug/components': typeof AppDebugComponentsRouteWithChildren
  '/_app/debug/errors': typeof AppDebugErrorsRoute
  '/_app/debug/notifications': typeof AppDebugNotificationsRoute
  '/studio-overlay/settings/debug': typeof StudioOverlaySettingsDebugRoute
  '/studio-overlay/settings/features': typeof StudioOverlaySettingsFeaturesRoute
  '/studio-overlay/settings/providers': typeof StudioOverlaySettingsProvidersRoute
  '/_app/debug/': typeof AppDebugIndexRoute
  '/_app/evals/': typeof AppEvalsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/studio-overlay/settings/': typeof StudioOverlaySettingsIndexRoute
  '/_app/debug/browser-view/$targetId': typeof AppDebugBrowserViewTargetIdRoute
  '/_app/debug/components/alerts': typeof AppDebugComponentsAlertsRoute
  '/_app/debug/components/chat-stream': typeof AppDebugComponentsChatStreamRoute
  '/_app/debug/components/colors': typeof AppDebugComponentsColorsRoute
  '/_app/debug/components/error-card': typeof AppDebugComponentsErrorCardRoute
  '/_app/debug/components/onboarding': typeof AppDebugComponentsOnboardingRouteWithChildren
  '/_app/debug/components/provider-icons': typeof AppDebugComponentsProviderIconsRoute
  '/_app/debug/components/spinner': typeof AppDebugComponentsSpinnerRoute
  '/_app/debug/components/update-status': typeof AppDebugComponentsUpdateStatusRoute
  '/_app/debug/components/': typeof AppDebugComponentsIndexRoute
  '/_app/projects/$subdomain/': typeof AppProjectsSubdomainIndexRoute
  '/_app/tasks/$id/': typeof AppTasksIdIndexRoute
  '/_app/debug/components/onboarding/complete': typeof AppDebugComponentsOnboardingCompleteRoute
  '/_app/debug/components/onboarding/login': typeof AppDebugComponentsOnboardingLoginRoute
  '/_app/debug/components/onboarding/providers': typeof AppDebugComponentsOnboardingProvidersRoute
  '/_app/debug/components/onboarding/theme': typeof AppDebugComponentsOnboardingThemeRoute
  '/_app/debug/components/onboarding/': typeof AppDebugComponentsOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/shell'
    | '/studio-overlay'
    | '/studio-overlay-idle'
    | '/debug'
    | '/new-tab'
    | '/release-notes'
    | '/tutorial-task'
    | '/onboarding/providers'
    | '/onboarding/theme'
    | '/studio-overlay/crash'
    | '/studio-overlay/login'
    | '/studio-overlay/settings'
    | '/studio-overlay/welcome'
    | '/onboarding/'
    | '/subscribe'
    | '/debug/browser-views'
    | '/debug/components'
    | '/debug/errors'
    | '/debug/notifications'
    | '/studio-overlay/settings/debug'
    | '/studio-overlay/settings/features'
    | '/studio-overlay/settings/providers'
    | '/debug/'
    | '/evals'
    | '/projects'
    | '/tasks'
    | '/studio-overlay/settings/'
    | '/debug/browser-view/$targetId'
    | '/debug/components/alerts'
    | '/debug/components/chat-stream'
    | '/debug/components/colors'
    | '/debug/components/error-card'
    | '/debug/components/onboarding'
    | '/debug/components/provider-icons'
    | '/debug/components/spinner'
    | '/debug/components/update-status'
    | '/debug/components/'
    | '/projects/$subdomain'
    | '/tasks/$id'
    | '/debug/components/onboarding/complete'
    | '/debug/components/onboarding/login'
    | '/debug/components/onboarding/providers'
    | '/debug/components/onboarding/theme'
    | '/debug/components/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shell'
    | '/studio-overlay'
    | '/studio-overlay-idle'
    | '/new-tab'
    | '/release-notes'
    | '/tutorial-task'
    | '/onboarding/providers'
    | '/onboarding/theme'
    | '/studio-overlay/crash'
    | '/studio-overlay/login'
    | '/studio-overlay/welcome'
    | '/onboarding'
    | '/subscribe'
    | '/debug/browser-views'
    | '/debug/errors'
    | '/debug/notifications'
    | '/studio-overlay/settings/debug'
    | '/studio-overlay/settings/features'
    | '/studio-overlay/settings/providers'
    | '/debug'
    | '/evals'
    | '/projects'
    | '/tasks'
    | '/studio-overlay/settings'
    | '/debug/browser-view/$targetId'
    | '/debug/components/alerts'
    | '/debug/components/chat-stream'
    | '/debug/components/colors'
    | '/debug/components/error-card'
    | '/debug/components/provider-icons'
    | '/debug/components/spinner'
    | '/debug/components/update-status'
    | '/debug/components'
    | '/projects/$subdomain'
    | '/tasks/$id'
    | '/debug/components/onboarding/complete'
    | '/debug/components/onboarding/login'
    | '/debug/components/onboarding/providers'
    | '/debug/components/onboarding/theme'
    | '/debug/components/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/shell'
    | '/studio-overlay'
    | '/studio-overlay-idle'
    | '/_app/_authenticated'
    | '/_app/debug'
    | '/_app/new-tab'
    | '/_app/release-notes'
    | '/_app/tutorial-task'
    | '/onboarding/providers'
    | '/onboarding/theme'
    | '/studio-overlay/crash'
    | '/studio-overlay/login'
    | '/studio-overlay/settings'
    | '/studio-overlay/welcome'
    | '/onboarding/'
    | '/_app/_authenticated/subscribe'
    | '/_app/debug/browser-views'
    | '/_app/debug/components'
    | '/_app/debug/errors'
    | '/_app/debug/notifications'
    | '/studio-overlay/settings/debug'
    | '/studio-overlay/settings/features'
    | '/studio-overlay/settings/providers'
    | '/_app/debug/'
    | '/_app/evals/'
    | '/_app/projects/'
    | '/_app/tasks/'
    | '/studio-overlay/settings/'
    | '/_app/debug/browser-view/$targetId'
    | '/_app/debug/components/alerts'
    | '/_app/debug/components/chat-stream'
    | '/_app/debug/components/colors'
    | '/_app/debug/components/error-card'
    | '/_app/debug/components/onboarding'
    | '/_app/debug/components/provider-icons'
    | '/_app/debug/components/spinner'
    | '/_app/debug/components/update-status'
    | '/_app/debug/components/'
    | '/_app/projects/$subdomain/'
    | '/_app/tasks/$id/'
    | '/_app/debug/components/onboarding/complete'
    | '/_app/debug/components/onboarding/login'
    | '/_app/debug/components/onboarding/providers'
    | '/_app/debug/components/onboarding/theme'
    | '/_app/debug/components/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  ShellRoute: typeof ShellRoute
  StudioOverlayRoute: typeof StudioOverlayRouteWithChildren
  StudioOverlayIdleRoute: typeof StudioOverlayIdleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio-overlay-idle': {
      id: '/studio-overlay-idle'
      path: '/studio-overlay-idle'
      fullPath: '/studio-overlay-idle'
      preLoaderRoute: typeof StudioOverlayIdleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-overlay': {
      id: '/studio-overlay'
      path: '/studio-overlay'
      fullPath: '/studio-overlay'
      preLoaderRoute: typeof StudioOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shell': {
      id: '/shell'
      path: '/shell'
      fullPath: '/shell'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/studio-overlay/welcome': {
      id: '/studio-overlay/welcome'
      path: '/welcome'
      fullPath: '/studio-overlay/welcome'
      preLoaderRoute: typeof StudioOverlayWelcomeRouteImport
      parentRoute: typeof StudioOverlayRoute
    }
    '/studio-overlay/settings': {
      id: '/studio-overlay/settings'
      path: '/settings'
      fullPath: '/studio-overlay/settings'
      preLoaderRoute: typeof StudioOverlaySettingsRouteImport
      parentRoute: typeof StudioOverlayRoute
    }
    '/studio-overlay/login': {
      id: '/studio-overlay/login'
      path: '/login'
      fullPath: '/studio-overlay/login'
      preLoaderRoute: typeof StudioOverlayLoginRouteImport
      parentRoute: typeof StudioOverlayRoute
    }
    '/studio-overlay/crash': {
      id: '/studio-overlay/crash'
      path: '/crash'
      fullPath: '/studio-overlay/crash'
      preLoaderRoute: typeof StudioOverlayCrashRouteImport
      parentRoute: typeof StudioOverlayRoute
    }
    '/onboarding/theme': {
      id: '/onboarding/theme'
      path: '/theme'
      fullPath: '/onboarding/theme'
      preLoaderRoute: typeof OnboardingThemeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/providers': {
      id: '/onboarding/providers'
      path: '/providers'
      fullPath: '/onboarding/providers'
      preLoaderRoute: typeof OnboardingProvidersRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_app/tutorial-task': {
      id: '/_app/tutorial-task'
      path: '/tutorial-task'
      fullPath: '/tutorial-task'
      preLoaderRoute: typeof AppTutorialTaskRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/release-notes': {
      id: '/_app/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof AppReleaseNotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/new-tab': {
      id: '/_app/new-tab'
      path: '/new-tab'
      fullPath: '/new-tab'
      preLoaderRoute: typeof AppNewTabRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/debug': {
      id: '/_app/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AppDebugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/studio-overlay/settings/': {
      id: '/studio-overlay/settings/'
      path: '/'
      fullPath: '/studio-overlay/settings/'
      preLoaderRoute: typeof StudioOverlaySettingsIndexRouteImport
      parentRoute: typeof StudioOverlaySettingsRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/evals/': {
      id: '/_app/evals/'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof AppEvalsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/debug/': {
      id: '/_app/debug/'
      path: '/'
      fullPath: '/debug/'
      preLoaderRoute: typeof AppDebugIndexRouteImport
      parentRoute: typeof AppDebugRouteRoute
    }
    '/studio-overlay/settings/providers': {
      id: '/studio-overlay/settings/providers'
      path: '/providers'
      fullPath: '/studio-overlay/settings/providers'
      preLoaderRoute: typeof StudioOverlaySettingsProvidersRouteImport
      parentRoute: typeof StudioOverlaySettingsRoute
    }
    '/studio-overlay/settings/features': {
      id: '/studio-overlay/settings/features'
      path: '/features'
      fullPath: '/studio-overlay/settings/features'
      preLoaderRoute: typeof StudioOverlaySettingsFeaturesRouteImport
      parentRoute: typeof StudioOverlaySettingsRoute
    }
    '/studio-overlay/settings/debug': {
      id: '/studio-overlay/settings/debug'
      path: '/debug'
      fullPath: '/studio-overlay/settings/debug'
      preLoaderRoute: typeof StudioOverlaySettingsDebugRouteImport
      parentRoute: typeof StudioOverlaySettingsRoute
    }
    '/_app/debug/notifications': {
      id: '/_app/debug/notifications'
      path: '/notifications'
      fullPath: '/debug/notifications'
      preLoaderRoute: typeof AppDebugNotificationsRouteImport
      parentRoute: typeof AppDebugRouteRoute
    }
    '/_app/debug/errors': {
      id: '/_app/debug/errors'
      path: '/errors'
      fullPath: '/debug/errors'
      preLoaderRoute: typeof AppDebugErrorsRouteImport
      parentRoute: typeof AppDebugRouteRoute
    }
    '/_app/debug/components': {
      id: '/_app/debug/components'
      path: '/components'
      fullPath: '/debug/components'
      preLoaderRoute: typeof AppDebugComponentsRouteImport
      parentRoute: typeof AppDebugRouteRoute
    }
    '/_app/debug/browser-views': {
      id: '/_app/debug/browser-views'
      path: '/browser-views'
      fullPath: '/debug/browser-views'
      preLoaderRoute: typeof AppDebugBrowserViewsRouteImport
      parentRoute: typeof AppDebugRouteRoute
    }
    '/_app/_authenticated/subscribe': {
      id: '/_app/_authenticated/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof AppAuthenticatedSubscribeRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/tasks/$id/': {
      id: '/_app/tasks/$id/'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AppTasksIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/$subdomain/': {
      id: '/_app/projects/$subdomain/'
      path: '/projects/$subdomain'
      fullPath: '/projects/$subdomain'
      preLoaderRoute: typeof AppProjectsSubdomainIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/debug/components/': {
      id: '/_app/debug/components/'
      path: '/'
      fullPath: '/debug/components/'
      preLoaderRoute: typeof AppDebugComponentsIndexRouteImport
      parentRoute: typeof AppDebugComponentsRoute
    }
    '/_app/debug/components/update-status': {
      id: '/_app/debug/components/update-status'
      path: '/update-status'
      fullPath: '/debug/components/update-status'
      preLoaderRoute: typeof AppDebugComponentsUpdateStatusRouteImport
      parentRoute: typeof AppDebugComponentsRoute
    }
    '/_app/debug/components/spinner': {
      id: '/_app/debug/components/spinner'
      path: '/spinner'
      fullPath: '/debug/components/spinner'
      preLoaderRoute: typeof AppDebugComponentsSpinnerRouteImport
      parentRoute: typeof AppDebugComponentsRoute
    }
    '/_app/debug/components/provider-icons': {
      id: '/_app/debug/components/provider-icons'
      path: '/provider-icons'
      fullPath: '/debug/components/provider-icons'
      preLoaderRoute: typeof AppDebugComponentsProviderIconsRouteImport
      parentRoute: typeof AppDebugComponentsRoute
    }
    '/_app/debug/components/onboarding': {
      id: '/_app/debug/components/onboarding'
      path: '/onboarding'
      fullPath: '/debug/components/onboarding'
      preLoaderRoute: typeof AppDebugComponentsOnboardingRouteImport
      parentRoute: typeof AppDebugComponentsRoute
    }
    '/_app/debug/components/error-card': {
      id: '/_app/debug/components/error-card'
      path: '/error-card'
      fullPath: '/debug/components/error-card'
      preLoaderRoute: typeof AppDebugComponentsErrorCardRouteImport
      parentRoute: typeof AppDebugComponentsRoute
    }
    '/_app/debug/components/colors': {
      id: '/_app/debug/components/colors'
      path: '/colors'
      fullPath: '/debug/components/colors'
      preLoaderRoute: typeof AppDebugComponentsColorsRouteImport
      parentRoute: typeof AppDebugComponentsRoute
    }
    '/_app/debug/components/chat-stream': {
      id: '/_app/debug/components/chat-stream'
      path: '/chat-stream'
      fullPath: '/debug/components/chat-stream'
      preLoaderRoute: typeof AppDebugComponentsChatStreamRouteImport
      parentRoute: typeof AppDebugComponentsRoute
    }
    '/_app/debug/components/alerts': {
      id: '/_app/debug/components/alerts'
      path: '/alerts'
      fullPath: '/debug/components/alerts'
      preLoaderRoute: typeof AppDebugComponentsAlertsRouteImport
      parentRoute: typeof AppDebugComponentsRoute
    }
    '/_app/debug/browser-view/$targetId': {
      id: '/_app/debug/browser-view/$targetId'
      path: '/browser-view/$targetId'
      fullPath: '/debug/browser-view/$targetId'
      preLoaderRoute: typeof AppDebugBrowserViewTargetIdRouteImport
      parentRoute: typeof AppDebugRouteRoute
    }
    '/_app/debug/components/onboarding/': {
      id: '/_app/debug/components/onboarding/'
      path: '/'
      fullPath: '/debug/components/onboarding/'
      preLoaderRoute: typeof AppDebugComponentsOnboardingIndexRouteImport
      parentRoute: typeof AppDebugComponentsOnboardingRoute
    }
    '/_app/debug/components/onboarding/theme': {
      id: '/_app/debug/components/onboarding/theme'
      path: '/theme'
      fullPath: '/debug/components/onboarding/theme'
      preLoaderRoute: typeof AppDebugComponentsOnboardingThemeRouteImport
      parentRoute: typeof AppDebugComponentsOnboardingRoute
    }
    '/_app/debug/components/onboarding/providers': {
      id: '/_app/debug/components/onboarding/providers'
      path: '/providers'
      fullPath: '/debug/components/onboarding/providers'
      preLoaderRoute: typeof AppDebugComponentsOnboardingProvidersRouteImport
      parentRoute: typeof AppDebugComponentsOnboardingRoute
    }
    '/_app/debug/components/onboarding/login': {
      id: '/_app/debug/components/onboarding/login'
      path: '/login'
      fullPath: '/debug/components/onboarding/login'
      preLoaderRoute: typeof AppDebugComponentsOnboardingLoginRouteImport
      parentRoute: typeof AppDebugComponentsOnboardingRoute
    }
    '/_app/debug/components/onboarding/complete': {
      id: '/_app/debug/components/onboarding/complete'
      path: '/complete'
      fullPath: '/debug/components/onboarding/complete'
      preLoaderRoute: typeof AppDebugComponentsOnboardingCompleteRouteImport
      parentRoute: typeof AppDebugComponentsOnboardingRoute
    }
  }
}

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedSubscribeRoute: typeof AppAuthenticatedSubscribeRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedSubscribeRoute: AppAuthenticatedSubscribeRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppDebugComponentsOnboardingRouteChildren {
  AppDebugComponentsOnboardingCompleteRoute: typeof AppDebugComponentsOnboardingCompleteRoute
  AppDebugComponentsOnboardingLoginRoute: typeof AppDebugComponentsOnboardingLoginRoute
  AppDebugComponentsOnboardingProvidersRoute: typeof AppDebugComponentsOnboardingProvidersRoute
  AppDebugComponentsOnboardingThemeRoute: typeof AppDebugComponentsOnboardingThemeRoute
  AppDebugComponentsOnboardingIndexRoute: typeof AppDebugComponentsOnboardingIndexRoute
}

const AppDebugComponentsOnboardingRouteChildren: AppDebugComponentsOnboardingRouteChildren =
  {
    AppDebugComponentsOnboardingCompleteRoute:
      AppDebugComponentsOnboardingCompleteRoute,
    AppDebugComponentsOnboardingLoginRoute:
      AppDebugComponentsOnboardingLoginRoute,
    AppDebugComponentsOnboardingProvidersRoute:
      AppDebugComponentsOnboardingProvidersRoute,
    AppDebugComponentsOnboardingThemeRoute:
      AppDebugComponentsOnboardingThemeRoute,
    AppDebugComponentsOnboardingIndexRoute:
      AppDebugComponentsOnboardingIndexRoute,
  }

const AppDebugComponentsOnboardingRouteWithChildren =
  AppDebugComponentsOnboardingRoute._addFileChildren(
    AppDebugComponentsOnboardingRouteChildren,
  )

interface AppDebugComponentsRouteChildren {
  AppDebugComponentsAlertsRoute: typeof AppDebugComponentsAlertsRoute
  AppDebugComponentsChatStreamRoute: typeof AppDebugComponentsChatStreamRoute
  AppDebugComponentsColorsRoute: typeof AppDebugComponentsColorsRoute
  AppDebugComponentsErrorCardRoute: typeof AppDebugComponentsErrorCardRoute
  AppDebugComponentsOnboardingRoute: typeof AppDebugComponentsOnboardingRouteWithChildren
  AppDebugComponentsProviderIconsRoute: typeof AppDebugComponentsProviderIconsRoute
  AppDebugComponentsSpinnerRoute: typeof AppDebugComponentsSpinnerRoute
  AppDebugComponentsUpdateStatusRoute: typeof AppDebugComponentsUpdateStatusRoute
  AppDebugComponentsIndexRoute: typeof AppDebugComponentsIndexRoute
}

const AppDebugComponentsRouteChildren: AppDebugComponentsRouteChildren = {
  AppDebugComponentsAlertsRoute: AppDebugComponentsAlertsRoute,
  AppDebugComponentsChatStreamRoute: AppDebugComponentsChatStreamRoute,
  AppDebugComponentsColorsRoute: AppDebugComponentsColorsRoute,
  AppDebugComponentsErrorCardRoute: AppDebugComponentsErrorCardRoute,
  AppDebugComponentsOnboardingRoute:
    AppDebugComponentsOnboardingRouteWithChildren,
  AppDebugComponentsProviderIconsRoute: AppDebugComponentsProviderIconsRoute,
  AppDebugComponentsSpinnerRoute: AppDebugComponentsSpinnerRoute,
  AppDebugComponentsUpdateStatusRoute: AppDebugComponentsUpdateStatusRoute,
  AppDebugComponentsIndexRoute: AppDebugComponentsIndexRoute,
}

const AppDebugComponentsRouteWithChildren =
  AppDebugComponentsRoute._addFileChildren(AppDebugComponentsRouteChildren)

interface AppDebugRouteRouteChildren {
  AppDebugBrowserViewsRoute: typeof AppDebugBrowserViewsRoute
  AppDebugComponentsRoute: typeof AppDebugComponentsRouteWithChildren
  AppDebugErrorsRoute: typeof AppDebugErrorsRoute
  AppDebugNotificationsRoute: typeof AppDebugNotificationsRoute
  AppDebugIndexRoute: typeof AppDebugIndexRoute
  AppDebugBrowserViewTargetIdRoute: typeof AppDebugBrowserViewTargetIdRoute
}

const AppDebugRouteRouteChildren: AppDebugRouteRouteChildren = {
  AppDebugBrowserViewsRoute: AppDebugBrowserViewsRoute,
  AppDebugComponentsRoute: AppDebugComponentsRouteWithChildren,
  AppDebugErrorsRoute: AppDebugErrorsRoute,
  AppDebugNotificationsRoute: AppDebugNotificationsRoute,
  AppDebugIndexRoute: AppDebugIndexRoute,
  AppDebugBrowserViewTargetIdRoute: AppDebugBrowserViewTargetIdRoute,
}

const AppDebugRouteRouteWithChildren = AppDebugRouteRoute._addFileChildren(
  AppDebugRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppDebugRouteRoute: typeof AppDebugRouteRouteWithChildren
  AppNewTabRoute: typeof AppNewTabRoute
  AppReleaseNotesRoute: typeof AppReleaseNotesRoute
  AppTutorialTaskRoute: typeof AppTutorialTaskRoute
  AppEvalsIndexRoute: typeof AppEvalsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppProjectsSubdomainIndexRoute: typeof AppProjectsSubdomainIndexRoute
  AppTasksIdIndexRoute: typeof AppTasksIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppDebugRouteRoute: AppDebugRouteRouteWithChildren,
  AppNewTabRoute: AppNewTabRoute,
  AppReleaseNotesRoute: AppReleaseNotesRoute,
  AppTutorialTaskRoute: AppTutorialTaskRoute,
  AppEvalsIndexRoute: AppEvalsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppProjectsSubdomainIndexRoute: AppProjectsSubdomainIndexRoute,
  AppTasksIdIndexRoute: AppTasksIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingProvidersRoute: typeof OnboardingProvidersRoute
  OnboardingThemeRoute: typeof OnboardingThemeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingProvidersRoute: OnboardingProvidersRoute,
  OnboardingThemeRoute: OnboardingThemeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface StudioOverlaySettingsRouteChildren {
  StudioOverlaySettingsDebugRoute: typeof StudioOverlaySettingsDebugRoute
  StudioOverlaySettingsFeaturesRoute: typeof StudioOverlaySettingsFeaturesRoute
  StudioOverlaySettingsProvidersRoute: typeof StudioOverlaySettingsProvidersRoute
  StudioOverlaySettingsIndexRoute: typeof StudioOverlaySettingsIndexRoute
}

const StudioOverlaySettingsRouteChildren: StudioOverlaySettingsRouteChildren = {
  StudioOverlaySettingsDebugRoute: StudioOverlaySettingsDebugRoute,
  StudioOverlaySettingsFeaturesRoute: StudioOverlaySettingsFeaturesRoute,
  StudioOverlaySettingsProvidersRoute: StudioOverlaySettingsProvidersRoute,
  StudioOverlaySettingsIndexRoute: StudioOverlaySettingsIndexRoute,
}

const StudioOverlaySettingsRouteWithChildren =
  StudioOverlaySettingsRoute._addFileChildren(
    StudioOverlaySettingsRouteChildren,
  )

interface StudioOverlayRouteChildren {
  StudioOverlayCrashRoute: typeof StudioOverlayCrashRoute
  StudioOverlayLoginRoute: typeof StudioOverlayLoginRoute
  StudioOverlaySettingsRoute: typeof StudioOverlaySettingsRouteWithChildren
  StudioOverlayWelcomeRoute: typeof StudioOverlayWelcomeRoute
}

const StudioOverlayRouteChildren: StudioOverlayRouteChildren = {
  StudioOverlayCrashRoute: StudioOverlayCrashRoute,
  StudioOverlayLoginRoute: StudioOverlayLoginRoute,
  StudioOverlaySettingsRoute: StudioOverlaySettingsRouteWithChildren,
  StudioOverlayWelcomeRoute: StudioOverlayWelcomeRoute,
}

const StudioOverlayRouteWithChildren = StudioOverlayRoute._addFileChildren(
  StudioOverlayRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  ShellRoute: ShellRoute,
  StudioOverlayRoute: StudioOverlayRouteWithChildren,
  StudioOverlayIdleRoute: StudioOverlayIdleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
