// Capture a real conversation as a committed fixture transcript.
//
//   pnpm --filter @instrument-org/workspace script:record-fixture-session \
//     <task-dir> --fixture documents --task attention-paper
//
//   pnpm --filter @instrument-org/workspace script:record-fixture-session \
//     <chat-dir> --fixture documents --chat red-and-blue-squares \
//     --task-key t1=generated-pdf
//
// A chat is recorded with every task it started, each a session in its store,
// read without the conversation it carried on from. The chat's id is renamed to
// its fixture key wherever the transcripts name it; `--task-key <handle>=<key>`
// picks a task's key, which is its handle (`t1`) otherwise. A `<task-dir>` is a
// folder holding one conversation of its own, as 1.x left a task.
//
// Transcripts are recorded from a run that actually happened, never authored by
// hand and never regenerated by asking a model: what makes a fixture worth
// keeping is that it is a thing the app really produced. Seeding replays what is
// captured here verbatim, so whatever the transcript says the tools returned is
// what the seeded task will show.
//
// Input files the task depends on are not captured. They belong beside the
// transcript in `files/`, declared in the manifest, and copied into the seeded
// task -- they are inert, and regenerating them would defeat the point of
// committing the exact file that broke something.

import "./lib/define-globals-apply";

import {
  PRIVATE_FOLDER_NAME,
  SETTINGS_FILE_NAME,
} from "@instrument-org/shared";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { parseArgs } from "node:util";
import superjson from "superjson";

import { TASKS_DIR_NAME } from "../src/constants";
import { listChildTasks } from "../src/lib/chat/children";
import { placeChat, resolveChat } from "../src/lib/record-folders";
import { Store } from "../src/lib/store";
import { setWorkspaceConfig } from "../src/lib/workspace-config";
import {
  AbsolutePathSchema,
  type ChatDir,
  ChatDirSchema,
} from "../src/schemas/paths";
import { type Session } from "../src/schemas/session";
import { type SessionMessagePart } from "../src/schemas/session/message-part";
import { StoreId } from "../src/schemas/store-id";
import { ChatIdSchema } from "../src/schemas/chat-id";
import { createStubWorkspaceConfig } from "./lib/stub-workspace-config";
import {
  fixtureChatSessionPath,
  fixtureSessionPath,
} from "./lib/workspace-fixture";

const { positionals, values } = parseArgs({
  allowPositionals: true,
  options: {
    "allow-local-paths": { default: false, type: "boolean" },
    chat: { type: "string" },
    fixture: { type: "string" },
    session: { type: "string" },
    task: { type: "string" },
    "task-key": { multiple: true, type: "string" },
  },
});

const inputPath = positionals[0];
if (!inputPath || !values.fixture || !(values.task ?? values.chat)) {
  throw new TypeError(
    "Usage: pnpm run script:record-fixture-session <task-dir> --fixture <name> --task <key> [--session <id>]\n       pnpm run script:record-fixture-session <chat-dir> --fixture <name> --chat <key> [--task-key <handle>=<key>]...",
  );
}

if (values.chat) {
  await recordChat({
    chatDir: path.resolve(inputPath),
    chatKey: values.chat,
    fixture: values.fixture,
  });
  process.exit(0);
}
await recordTask({
  fixture: values.fixture,
  chatDir: ChatDirSchema.parse(path.resolve(inputPath)),
  taskKey: values.task ?? "",
});

/**
 * Record a lone conversation as one fixture transcript: a 1.x task's folder,
 * read through the chat index pointed at the folder it sits in.
 */
async function recordTask({
  fixture,
  chatDir,
  taskKey,
}: {
  fixture: string;
  chatDir: ChatDir;
  taskKey: string;
}) {
  setWorkspaceConfig({
    ...createStubWorkspaceConfig({ tasksDir: path.dirname(chatDir) }),
    chatsDir: AbsolutePathSchema.parse(path.dirname(chatDir)),
  });
  const id = ChatIdSchema.parse(path.basename(chatDir));
  if (resolveChat(id) === undefined) {
    placeChat(id, StoreId.newSessionId());
  }
  const recorded = await readSession(id);
  assertNoLocalPaths(recorded);

  const written = fixtureSessionPath(fixture, taskKey);
  await fs.mkdir(path.dirname(written), { recursive: true });
  // superjson rather than plain JSON: the session schemas require real `Date`s,
  // and a transcript that loses them fails to parse at seed time.
  await fs.writeFile(written, `${superjson.stringify(recorded)}\n`);

  process.stdout.write(
    `Recorded ${recorded.messages.length} message(s) from session ${recorded.id} to ${written}\n`,
  );
}

/**
 * A transcript is committed, so it must not carry one developer's disk. Refuses
 * rather than rewriting: a host path inside a tool result usually means the run
 * did something machine-specific, and quietly substituting a placeholder would
 * hide that behind a fixture that no longer describes a real run.
 */
function assertNoLocalPaths(
  session: Session.WithMessagesAndParts,
  extraNeedles: string[] = [],
) {
  if (values["allow-local-paths"]) {
    return;
  }

  const needles = [
    os.homedir(),
    path.resolve(import.meta.dirname, "../../.."),
    ...extraNeedles,
  ];
  const serialized = superjson.stringify(session);
  // Searched in both raw and JSON-escaped form. superjson goes through
  // JSON.stringify, so a Windows path arrives in the text with its separators
  // doubled and a raw search for `C:\Users\someone` finds nothing -- the guard
  // would pass on exactly the platform where the paths look least like the
  // POSIX ones it was written against.
  const found = needles.filter(
    (needle) =>
      serialized.includes(needle) ||
      serialized.includes(JSON.stringify(needle).slice(1, -1)),
  );

  if (found.length > 0) {
    throw new Error(
      [
        "Transcript contains machine-local paths and was not written:",
        ...found.map((needle) => `  ${needle}`),
        "Re-record from a run that does not reference them, or pass --allow-local-paths",
        "if you have checked that every occurrence is safe to commit.",
      ].join("\n"),
    );
  }
}

async function readSession(
  chatId: ReturnType<typeof ChatIdSchema.parse>,
  preferred?: string,
  { inherited = true }: { inherited?: boolean } = {},
): Promise<Session.WithMessagesAndParts> {
  const sessionIdsResult = await Store.getStoreId(chatId);
  if (sessionIdsResult.isErr()) {
    throw sessionIdsResult.error;
  }
  const sessionIds = sessionIdsResult.value;

  if (sessionIds.length === 0) {
    throw new Error(`${chatId} has no sessions`);
  }

  const requested =
    (preferred ?? values.session)
      ? StoreId.SessionSchema.parse(preferred ?? values.session)
      : // Ids are ULIDs, so the last one is the most recent session.
        sessionIds.toSorted().at(-1);

  const sessionId = sessionIds.find((id) => id === requested);
  if (!sessionId) {
    throw new Error(
      `No session ${String(requested)} in ${chatId}. Available:\n${sessionIds.map((id) => `  ${id}`).join("\n")}`,
    );
  }

  const session = await Store.getSession(sessionId, chatId);
  if (session.isErr()) {
    throw session.error;
  }
  const messages = await Store.getMessagesWithParts({
    chatId,
    inherited,
    sessionId,
  });
  if (messages.isErr()) {
    throw messages.error;
  }
  return {
    ...session.value,
    // The session-context message is a persisted snapshot of the system prompt
    // and the host's own details. Committing one would pin a copy of the prompt
    // into the corpus, to go stale the next time it is edited, and it buys
    // nothing: the app rebuilds it when a session next takes a turn, and it
    // renders nowhere outside the developer-mode context card.
    messages: messages.value.filter(
      (message) => message.role !== "session-context",
    ),
  };
}

/**
 * Records a chat and every task it started. The workspace the chat sits in is
 * the one the store reads through, so the chat index finds the chat and its
 * store holds its tasks. The folders the chat was granted are machine paths
 * too, and are refused like the home folder.
 */
async function recordChat({
  chatDir,
  chatKey,
  fixture,
}: {
  chatDir: string;
  chatKey: string;
  fixture: string;
}) {
  const rootDir = path.dirname(path.dirname(chatDir));
  setWorkspaceConfig(
    createStubWorkspaceConfig({
      rootDir: AbsolutePathSchema.parse(rootDir),
      tasksDir: AbsolutePathSchema.parse(path.join(rootDir, TASKS_DIR_NAME)),
    }),
  );
  const chatId = ChatIdSchema.parse(path.basename(chatDir));
  const settings = JSON.parse(
    await fs.readFile(
      path.join(chatDir, PRIVATE_FOLDER_NAME, SETTINGS_FILE_NAME),
      "utf8",
    ),
  ) as { chatSessionId?: string; grants?: { path: string }[] };
  const folderPaths = (settings.grants ?? []).map((grant) => grant.path);

  const taskKeys = new Map<string, string>();
  for (const pair of values["task-key"] ?? []) {
    const [handle, key] = pair.split("=");
    if (!handle || !key) {
      throw new TypeError(`--task-key takes <handle>=<key>, not ${pair}`);
    }
    taskKeys.set(handle, key);
  }

  const renamed = (session: Session.WithMessagesAndParts) =>
    superjson.parse<Session.WithMessagesAndParts>(
      superjson
        .stringify(withoutFolderGrants(session))
        .replaceAll(chatId, chatKey),
    );

  const written: string[] = [];
  const chatSession = renamed(
    await readSession(chatId, settings.chatSessionId),
  );
  assertNoLocalPaths(chatSession, folderPaths);
  const chatPath = fixtureChatSessionPath(fixture, chatKey);
  for (const task of await listChildTasks(chatId)) {
    const session = renamed(
      await readSession(chatId, task.id, { inherited: false }),
    );
    assertNoLocalPaths(session, folderPaths);
    const outputPath = fixtureSessionPath(
      fixture,
      taskKeys.get(task.handle) ?? task.handle,
      chatKey,
    );
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, `${superjson.stringify(session)}\n`);
    written.push(outputPath);
  }
  await fs.mkdir(path.dirname(chatPath), { recursive: true });
  await fs.writeFile(chatPath, `${superjson.stringify(chatSession)}\n`);
  written.unshift(chatPath);

  process.stdout.write(
    `Recorded:\n${written.map((file) => `  ${file}`).join("\n")}\n`,
  );
}

/**
 * The folders a chat was sent ride on the message they came with, by their
 * paths on the recording machine. The manifest declares a chat's folders and
 * the seeder makes them, so the recorded grants are dropped rather than
 * committed: a part left with no files goes whole.
 */
function withoutFolderGrants(
  session: Session.WithMessagesAndParts,
): Session.WithMessagesAndParts {
  return {
    ...session,
    messages: session.messages.map((message) => ({
      ...message,
      parts: message.parts.flatMap((part): SessionMessagePart.Type[] => {
        if (part.type !== "data-attachments") {
          return [part];
        }
        const { folders: _folders, ...data } = part.data;
        return data.files.length > 0 ? [{ ...part, data }] : [];
      }),
    })),
  };
}
