blank_issues_enabled: false
contact_links:
  - about: Our preferred starting point if you have any questions, feature requests, or bug reports.
    name: Bug Reports, Feature Requests & Questions
    url: https://github.com/instrument-org/instrument/discussions/new/choose
