import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

/**
 * Where the agent's agent-browser guide comes from: the core guide the
 * installed CLI release ships (`skill-data/core`, the text
 * `agent-browser skills get core` prints), with the sections about setting
 * agent-browser up elsewhere left out. Read by the refresh script, which
 * writes the result into `agent-browser-core-guide.generated.ts`, and by the
 * test that fails when that file no longer matches the installed release.
 * Nothing here runs in the app.
 */

/** The upstream sections that describe a setup this app does for the agent, by their exact heading. */
export const LEFT_OUT_SECTIONS = [
  "## Always use your own session",
  "## Quickstart",
  "## MCP integration",
  "## eve agent integration",
  "### Persist session across runs",
  "### Run multiple browsers in parallel",
  "## Diagnosing install issues",
  "## Global flags worth knowing",
  "## Observability Dashboard",
  "## When to load another skill",
] as const;

/** The references the guide links to that apply here, kept for `skills get core --full`. */
const REFERENCE_FILES = [
  "commands.md",
  "snapshot-refs.md",
  "trust-boundaries.md",
] as const;

const req = createRequire(import.meta.url);

/** The installed agent-browser release, and its core guide's folder. */
export function installedAgentBrowser(): { coreDir: string; version: string } {
  const packageJson = req.resolve("agent-browser/package.json");
  const { version } = req(packageJson) as { version: string };
  return {
    coreDir: path.join(path.dirname(packageJson), "skill-data", "core"),
    version,
  };
}

/** The installed core guide as shipped, frontmatter removed, sections and all. */
export function upstreamCoreGuide(coreDir: string): string {
  return readFileSync(path.join(coreDir, "SKILL.md"), "utf8").replace(
    /^---\n[\s\S]*?\n---\n+/,
    "",
  );
}

/** The guide and its references as the agent reads them, from an installed release. */
export function coreGuideFrom(coreDir: string): {
  guide: string;
  references: string;
} {
  return {
    guide: withoutSections(upstreamCoreGuide(coreDir), LEFT_OUT_SECTIONS)
      .trim()
      .concat("\n"),
    references: REFERENCE_FILES.map(
      (name) =>
        `\n---\n\n<!-- references/${name} -->\n\n${readFileSync(path.join(coreDir, "references", name), "utf8").trim()}\n`,
    ).join(""),
  };
}

/**
 * A Markdown text with the named sections removed. A heading is a line
 * starting with `#` outside a fenced code block, whose shell comments start
 * the same way; a section runs to the next heading of its level or above.
 */
export function withoutSections(
  markdown: string,
  headings: readonly string[],
): string {
  const kept: string[] = [];
  let inFence = false;
  let skippingLevel: number | undefined;
  for (const line of markdown.split("\n")) {
    if (line.startsWith("```")) {
      inFence = !inFence;
    }
    const heading = inFence ? undefined : /^(#{1,6}) /.exec(line);
    if (heading?.[1] !== undefined) {
      const level = heading[1].length;
      if (skippingLevel !== undefined && level <= skippingLevel) {
        skippingLevel = undefined;
      }
      if (skippingLevel === undefined && headings.includes(line.trim())) {
        skippingLevel = level;
      }
    }
    if (skippingLevel === undefined) {
      kept.push(line);
    }
  }
  return kept.join("\n");
}

/** The headings of a Markdown text, outside fenced code. */
export function headingsOf(markdown: string): string[] {
  let inFence = false;
  return markdown.split("\n").flatMap((line) => {
    if (line.startsWith("```")) {
      inFence = !inFence;
      return [];
    }
    return !inFence && /^#{1,6} /.test(line) ? [line.trim()] : [];
  });
}

/** The generated module's text for an installed release. */
export function generatedGuideModule({
  guide,
  references,
  version,
}: {
  guide: string;
  references: string;
  version: string;
}): string {
  return [
    "// Generated by scripts/refresh-agent-browser-guide.ts from the installed",
    "// agent-browser release's skill-data/core. Do not edit; run the script.",
    "",
    `export const AGENT_BROWSER_CORE_GUIDE_READ_FROM = ${JSON.stringify(version)};`,
    "",
    `export const AGENT_BROWSER_CORE_GUIDE = ${JSON.stringify(guide)};`,
    "",
    `export const AGENT_BROWSER_CORE_REFERENCES = ${JSON.stringify(references)};`,
    "",
  ].join("\n");
}
