import { describe, expect, it } from "vitest";

import { asksModelNote } from "./asks-model-text";

describe("asksModelNote", () => {
  it("lists each place with where it is, how to reach it, and what to change", () => {
    expect(
      asksModelNote({
        asks: [
          {
            excerpt: "## Budget\nWe spent too much.",
            file: {
              mount: "/mnt/docs/plan.md",
              name: "plan.md",
              path: "/Users/me/docs/plan.md",
            },
            instruction: "Make this a table",
            target: "lines 12-13",
          },
          {
            context: "Status: generated by a script\nFed by data.json",
            excerpt: '<h1 class="title">Party</h1>',
            file: { name: "invite.html", path: "/tmp/invite.html" },
            instruction: "Bigger",
            target: "Heading · line 12",
          },
          {
            file: { name: "notes.txt", path: "/tmp/notes.txt" },
            instruction: "",
            target: "whole file",
          },
        ],
      }),
    ).toMatchInlineSnapshot(`
      "
      <instrument-system-note>
      The user marked 3 places in their files, each with what they want there: usually a change to make in the file, sometimes a question about it. "This", "here" and "it" in the message refer to these.
      </instrument-system-note>
      1. \`plan.md\`, lines 12-13 (\`/Users/me/docs/plan.md\`; you reach it at \`/mnt/docs/plan.md\`)
         > ## Budget
         > We spent too much.
         Asked: Make this a table
      2. \`invite.html\`, Heading · line 12 (\`/tmp/invite.html\`; no folder you can reach covers it: ask for it with request_folder)
         > <h1 class="title">Party</h1>
         Status: generated by a script
         Fed by data.json
         Asked: Bigger
      3. \`notes.txt\`, whole file (\`/tmp/notes.txt\`; no folder you can reach covers it: ask for it with request_folder)
         No instruction of its own: the message says what to do with it."
    `);
  });
});
