import { describe, expect, it, vi } from "vitest";

import { AbsolutePathSchema } from "../schemas/paths";
import { TaskIdSchema } from "../schemas/task-id";
import { createMockTaskConfig } from "../test/helpers/mock-task-config";
import { installPythonSkill } from "./install-python-skill";
import { taskVenvDir, taskVenvPython } from "./uv";

vi.mock(import("./run-uv"));

describe("installPythonSkill", () => {
  it("installs locked project dependencies into the task venv", async () => {
    const { runUvCommand } = await import("./run-uv");
    vi.mocked(runUvCommand)
      .mockResolvedValueOnce({ combined: "", exitCode: 0, stdout: "" })
      .mockResolvedValueOnce({
        combined: "",
        exitCode: 0,
        stdout: "# This file was autogenerated by uv\nexample==1.0\n",
      })
      .mockResolvedValueOnce({ combined: "", exitCode: 0, stdout: "" });

    const taskId = createMockTaskConfig(TaskIdSchema.parse("python-skill"));
    const skillDir = AbsolutePathSchema.parse("/tmp/skill");
    const signal = AbortSignal.timeout(10_000);

    await expect(
      installPythonSkill({ signal, skillDir, taskId }),
    ).resolves.toEqual({ state: "success" });

    expect(runUvCommand).toHaveBeenNthCalledWith(1, {
      args: ["venv", "--python", "3.12", taskVenvDir(taskId)],
      cwd: "/tmp/workspace/tasks/python-skill/work",
      signal: undefined,
      taskId,
    });
    expect(runUvCommand).toHaveBeenNthCalledWith(2, {
      args: [
        "export",
        "--locked",
        "--no-dev",
        "--no-emit-project",
        "--no-hashes",
        "--project",
        skillDir,
      ],
      cwd: "/tmp/workspace/tasks/python-skill/work",
      signal,
      taskId,
    });
    expect(runUvCommand).toHaveBeenNthCalledWith(3, {
      args: [
        "pip",
        "install",
        "--python",
        taskVenvPython(taskId),
        "--requirement",
        "-",
      ],
      cwd: "/tmp/workspace/tasks/python-skill/work",
      signal,
      stdin: "# This file was autogenerated by uv\nexample==1.0\n",
      taskId,
    });
  });

  it("returns the locked-export failure without attempting installation", async () => {
    const { runUvCommand } = await import("./run-uv");
    vi.mocked(runUvCommand)
      .mockResolvedValueOnce({ combined: "", exitCode: 0, stdout: "" })
      .mockResolvedValueOnce({
        combined: "lockfile is stale",
        exitCode: 2,
        stdout: "",
      });

    const taskId = createMockTaskConfig(TaskIdSchema.parse("stale-lock"));
    const result = await installPythonSkill({
      signal: AbortSignal.timeout(10_000),
      skillDir: AbsolutePathSchema.parse("/tmp/skill"),
      taskId,
    });

    expect(result).toEqual({
      exitCode: 2,
      output: "lockfile is stale",
      state: "failure",
    });
    expect(runUvCommand).toHaveBeenCalledTimes(2);
  });
});
