// The mime type an extension implies, for the extensions a mime database gets
// wrong or does not know at all -- source files, above all, which are text but
// resolve to `application/octet-stream` unless something says otherwise.
//
// Two readers, deriving different things from the same knowledge. The workspace
// server consults it ahead of the mime database when labeling a response's
// `Content-Type`. The renderer consults it when it has a filename and no mime
// type, which is every file reference drawn from a path alone.
//
export const CODE_EXTENSION_MIME_TYPES: Record<string, string> = {
  abap: "text/plain",
  ada: "text/plain",
  astro: "text/plain",
  bat: "text/plain",
  c: "text/plain",
  cjs: "text/javascript",
  clj: "text/plain",
  cljs: "text/plain",
  cmake: "text/plain",
  coffee: "text/plain",
  cpp: "text/plain",
  cs: "text/plain",
  css: "text/css",
  cts: "text/typescript",
  dart: "text/plain",
  diff: "text/plain",
  dockerfile: "text/plain",
  elm: "text/plain",
  erl: "text/plain",
  ex: "text/plain",
  exs: "text/plain",
  fish: "text/plain",
  fs: "text/plain",
  fsx: "text/plain",
  gd: "text/plain",
  gleam: "text/plain",
  glsl: "text/plain",
  go: "text/plain",
  graphql: "text/plain",
  groovy: "text/plain",
  h: "text/plain",
  haml: "text/plain",
  hbs: "text/plain",
  hpp: "text/plain",
  hs: "text/plain",
  hx: "text/plain",
  java: "text/plain",
  jl: "text/plain",
  // Line-delimited JSON is text, but `mime-types` knows neither extension, so
  // both resolved to `application/octet-stream` and the viewer showed the
  // "no preview" card. Not `application/json`, which they are not: each line
  // parses on its own, the file as a whole does not.
  jsonl: "text/plain",
  jsx: "text/jsx",
  kt: "text/plain",
  latex: "text/plain",
  less: "text/plain",
  lisp: "text/plain",
  lua: "text/plain",
  m: "text/plain",
  makefile: "text/plain",
  md: "text/markdown",
  mdx: "text/plain",
  mjs: "text/javascript",
  ml: "text/plain",
  mts: "text/typescript",
  ndjson: "text/plain",
  nim: "text/plain",
  nix: "text/plain",
  objc: "text/plain",
  pas: "text/plain",
  patch: "text/plain",
  perl: "text/plain",
  php: "text/plain",
  pl: "text/plain",
  proto: "text/plain",
  ps1: "text/plain",
  pug: "text/plain",
  py: "text/plain",
  r: "text/plain",
  rb: "text/plain",
  rs: "text/plain",
  sass: "text/plain",
  scala: "text/plain",
  scheme: "text/plain",
  scss: "text/plain",
  sh: "text/plain",
  sol: "text/plain",
  sql: "text/plain",
  styl: "text/plain",
  svelte: "text/plain",
  swift: "text/plain",
  tcl: "text/plain",
  tex: "text/plain",
  toml: "text/plain",
  ts: "text/typescript",
  tsx: "text/tsx",
  vb: "text/plain",
  vim: "text/plain",
  vue: "text/plain",
  yaml: "text/plain",
  yml: "text/plain",
  zig: "text/plain",
  zsh: "text/plain",
};
